spring:
  main:
    #开启覆盖名称相同bean
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(8MrBC3CT0x8MJa+PUQQbvwyo+xK3glydbcIopHKLwVWsrGzdByA53hQmtrHtGLfG6jc0pTPZpYCdJvr26GnNvkGsEmgLgwlfdNuDJ7q7VM9ZmF2BupH/o3q6BCCr8Lobekys/14Qrd7qs5OrnibUPCCn4F+unsn+5lWoJiNFdSGRz2X+q+tLruWUZZ+UPiQ68llEiCq7DiwBuU5619FjwUsYmzjFjDlmtDPq+Ymx2FefZPswLadC9YPZqrvqZq0N)
    username: ENC(Ze6FRaaX2+TbJ6p01l1h2kDJD6sdZIjyIEVmOoy6AhI5q5AufdAPUoPmfSZH1ZX1)
    password: ENC(CA4GYOz552fzde29SLdKCQ2h7eyieghExFEmWm1oTf8FTQJm1QTnUWitLVJFq2R7)
  # 默认密码
  security:
    user:
      name: admin
      password: admin
  application:
    name: volunteer_administration
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      path: /
  messages:
    basename: lang/MESSAGE
  kafka:
    producer:
      # 发生错误后，消息重新发的次数
      retries: 0
      batch-size: 16348
      # 一个批次可以使用的内存大小
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      # acks=0 ： 生产者在成功写入消息之前不会等待任何来自服务器的响应。
      # acks=1 ： 只要集群的首领节点收到消息，生产者就会收到一个来自服务器成功响应。
      # acks=all ：只有当所有参与复制的节点全部收到消息时，生产者才会收到一个来自服务器的成功响应。
      acks: 1
    consumer:
      # 指定了消费者在读取一个没有偏移量的分区或者偏移量无效的情况下该作何处理
      group-id: test-consumer-group.test
      auto-offset-reset: latest
      enable-auto-commit: true
      heartbeat-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      # 在侦听器容器中运行的线程数。
      concurrency: 5
      #listner负责ack，每调用一次，就立即commit
      ack-mode: manual_immediate
      missing-topics-fatal: false
    bootstrap-servers: 119.96.113.206:9092
  redis:
    host: 119.96.113.206
    port: 6379
    password: 666666666
build:
  platform: JWT
kafka:
  producer:
    topic: testTopic
  consumer:
    topic: xxx
server:
  port: 8083
  servlet:
    session:
      cookie:
        http-only: true
  compression:
    # 开启压缩
    enabled: true
    # 开启压缩数据的最小长度
    min-response-size: 2048
    mime-types: text/html, text/xml, text/plain, text/css, application/javascript, application/json
mybatis:
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
  type-aliases-package: cn.imut.ncee.dao
  mapper-locations: classpath:dao/*Dao.xml

# Pagehelper分页配置
pagehelper:
  helper-dialect: mysql
  #reasonable：当设置为true时，pageNum <= 0时，显示第1页，pageNum 超过 pageSize时，显示最后一页
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    org:
      springframework:
        security: info
jasypt:
  encryptor:
    #盐值
    password: AreYouOK
    algorithm: PBEWITHHMACSHA512ANDAES_256
threadpool:
  #是否开启线程
  open_flag: true
  #核心线程数
  core_pool_size: 10
  #最大线程数
  max_pool_size: 200
  #队列大小
  queue_capacity: 400
  #空闲线程活跃时间(s)
  keep_alive_seconds: 60
  #线程池名称
  default_name: t-pool
zookeeper:
  # 是否开启
  enabled: true
  # 服务器地址
  server: 119.96.113.206
  # 命名空间
  nameSpace: test
  # 权限加密
  digest: xxx=xxx
  # 会话超时时间
  sessionTimeoutMs: 3000
  # 连接超时时间
  connectionTimeoutMs: 60000
  # 最大重试次数
  maxRetries: 2
  # 初始休眠时间
  baseSleepTimeMs: 1000
system:
  session:
      whiteList:
      greyList: