spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(8MrBC3CT0x8MJa+PUQQbvwyo+xK3glydbcIopHKLwVWsrGzdByA53hQmtrHtGLfG6jc0pTPZpYCdJvr26GnNvkGsEmgLgwlfdNuDJ7q7VM9ZmF2BupH/o3q6BCCr8Lobekys/14Qrd7qs5OrnibUPCCn4F+unsn+5lWoJiNFdSGRz2X+q+tLruWUZZ+UPiQ68llEiCq7DiwBuU5619FjwUsYmzjFjDlmtDPq+Ymx2FefZPswLadC9YPZqrvqZq0N)
    username: ENC(Ze6FRaaX2+TbJ6p01l1h2kDJD6sdZIjyIEVmOoy6AhI5q5AufdAPUoPmfSZH1ZX1)
    password: ENC(CA4GYOz552fzde29SLdKCQ2h7eyieghExFEmWm1oTf8FTQJm1QTnUWitLVJFq2R7)
  # 默认密码
  security:
    user:
      name: admin
      password: admin
server:
  port: 8083
mybatis:
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
  type-aliases-package: cn.imut.ncee.dao
  mapper-locations: classpath:dao/*Dao.xml

# Pagehelper分页配置
pagehelper:
  helper-dialect: mysql
  #reasonable：当设置为true时，pageNum <= 0时，显示第1页，pageNum 超过 pageSize时，显示最后一页
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    org:
      springframework:
        security: info
jasypt:
  encryptor:
    #盐值
    password: AreYouOK
    algorithm: PBEWITHHMACSHA512ANDAES_256
