// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/person.proto

package com.recommend.bootstrap.domain.protos;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.recommend.bootstrap.domain.entity.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * =1，=2 作为序列化后的二进制编码中的字段的唯一标签，也因此，1-15 比 16 会少一个字节，所以尽量使用 1-15 来指定常用字段。
   * </pre>
   *
   * <code>optional string name = 1;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <pre>
   * =1，=2 作为序列化后的二进制编码中的字段的唯一标签，也因此，1-15 比 16 会少一个字节，所以尽量使用 1-15 来指定常用字段。
   * </pre>
   *
   * <code>optional string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * =1，=2 作为序列化后的二进制编码中的字段的唯一标签，也因此，1-15 比 16 会少一个字节，所以尽量使用 1-15 来指定常用字段。
   * </pre>
   *
   * <code>optional string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 age = 2;</code>
   * @return Whether the age field is set.
   */
  boolean hasAge();
  /**
   * <code>optional int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>optional int32 sex = 3;</code>
   * @return Whether the sex field is set.
   */
  boolean hasSex();
  /**
   * <code>optional int32 sex = 3;</code>
   * @return The sex.
   */
  int getSex();
}
