// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/person.proto

package com.recommend.bootstrap.domain.protos;

public final class PersonProtos {
  private PersonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_recommend_bootstrap_domain_entity_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_recommend_bootstrap_domain_entity_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026resources/person.proto\022%com.recommend." +
      "bootstrap.domain.entity\"\010\n\006PersonB7\n%com" +
      ".recommend.bootstrap.domain.protosB\014Pers" +
      "onProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_recommend_bootstrap_domain_entity_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_recommend_bootstrap_domain_entity_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_recommend_bootstrap_domain_entity_Person_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
