// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/person.proto

package com.recommend.bootstrap.domain.protos;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.recommend.bootstrap.domain.entity.Person)
    com.google.protobuf.MessageOrBuilder {
}
