// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/person.proto

package com.recommend.bootstrap.domain.protos;

public final class PersonProtos {
  private PersonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_recommend_bootstrap_domain_entity_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_recommend_bootstrap_domain_entity_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026resources/person.proto\022%com.recommend." +
      "bootstrap.domain.entity\"\353\001\n\006Person\022\014\n\004st" +
      "r1\030\001 \001(\t\022\014\n\004str2\030\002 \001(\t\022\014\n\004str3\030\003 \001(\t\022\014\n\004" +
      "str4\030\004 \001(\t\022\014\n\004str5\030\005 \001(\t\022\n\n\002i1\030\006 \001(\005\022\n\n\002" +
      "i2\030\007 \001(\005\022\n\n\002i3\030\010 \001(\005\022\n\n\002i4\030\t \001(\005\022\n\n\002i5\030\n" +
      " \001(\005\022\n\n\002i6\030\013 \001(\005\022\n\n\002i7\030\014 \001(\005\022\n\n\002i8\030\r \001(\005" +
      "\022\n\n\002i9\030\016 \001(\005\022\013\n\003i10\030\017 \001(\005\022\n\n\002l1\030\020 \003(\t\022\n\n" +
      "\002l2\030\021 \003(\t\022\n\n\002l3\030\022 \003(\tB7\n%com.recommend.b" +
      "ootstrap.domain.protosB\014PersonProtosP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_recommend_bootstrap_domain_entity_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_recommend_bootstrap_domain_entity_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_recommend_bootstrap_domain_entity_Person_descriptor,
        new java.lang.String[] { "Str1", "Str2", "Str3", "Str4", "Str5", "I1", "I2", "I3", "I4", "I5", "I6", "I7", "I8", "I9", "I10", "L1", "L2", "L3", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
