// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/person.proto

package com.recommend.provider.domain.protos;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.recommend.bootstrap.domain.entity.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string str1 = 1;</code>
   * @return The str1.
   */
  String getStr1();
  /**
   * <code>string str1 = 1;</code>
   * @return The bytes for str1.
   */
  com.google.protobuf.ByteString
      getStr1Bytes();

  /**
   * <code>string str2 = 2;</code>
   * @return The str2.
   */
  String getStr2();
  /**
   * <code>string str2 = 2;</code>
   * @return The bytes for str2.
   */
  com.google.protobuf.ByteString
      getStr2Bytes();

  /**
   * <code>string str3 = 3;</code>
   * @return The str3.
   */
  String getStr3();
  /**
   * <code>string str3 = 3;</code>
   * @return The bytes for str3.
   */
  com.google.protobuf.ByteString
      getStr3Bytes();

  /**
   * <code>string str4 = 4;</code>
   * @return The str4.
   */
  String getStr4();
  /**
   * <code>string str4 = 4;</code>
   * @return The bytes for str4.
   */
  com.google.protobuf.ByteString
      getStr4Bytes();

  /**
   * <code>string str5 = 5;</code>
   * @return The str5.
   */
  String getStr5();
  /**
   * <code>string str5 = 5;</code>
   * @return The bytes for str5.
   */
  com.google.protobuf.ByteString
      getStr5Bytes();

  /**
   * <code>int32 i1 = 6;</code>
   * @return The i1.
   */
  int getI1();

  /**
   * <code>int32 i2 = 7;</code>
   * @return The i2.
   */
  int getI2();

  /**
   * <code>int32 i3 = 8;</code>
   * @return The i3.
   */
  int getI3();

  /**
   * <code>int32 i4 = 9;</code>
   * @return The i4.
   */
  int getI4();

  /**
   * <code>int32 i5 = 10;</code>
   * @return The i5.
   */
  int getI5();

  /**
   * <code>int32 i6 = 11;</code>
   * @return The i6.
   */
  int getI6();

  /**
   * <code>int32 i7 = 12;</code>
   * @return The i7.
   */
  int getI7();

  /**
   * <code>int32 i8 = 13;</code>
   * @return The i8.
   */
  int getI8();

  /**
   * <code>int32 i9 = 14;</code>
   * @return The i9.
   */
  int getI9();

  /**
   * <code>int32 i10 = 15;</code>
   * @return The i10.
   */
  int getI10();

  /**
   * <code>repeated string l1 = 16;</code>
   * @return A list containing the l1.
   */
  java.util.List<String>
      getL1List();
  /**
   * <code>repeated string l1 = 16;</code>
   * @return The count of l1.
   */
  int getL1Count();
  /**
   * <code>repeated string l1 = 16;</code>
   * @param index The index of the element to return.
   * @return The l1 at the given index.
   */
  String getL1(int index);
  /**
   * <code>repeated string l1 = 16;</code>
   * @param index The index of the value to return.
   * @return The bytes of the l1 at the given index.
   */
  com.google.protobuf.ByteString
      getL1Bytes(int index);

  /**
   * <code>repeated string l2 = 17;</code>
   * @return A list containing the l2.
   */
  java.util.List<String>
      getL2List();
  /**
   * <code>repeated string l2 = 17;</code>
   * @return The count of l2.
   */
  int getL2Count();
  /**
   * <code>repeated string l2 = 17;</code>
   * @param index The index of the element to return.
   * @return The l2 at the given index.
   */
  String getL2(int index);
  /**
   * <code>repeated string l2 = 17;</code>
   * @param index The index of the value to return.
   * @return The bytes of the l2 at the given index.
   */
  com.google.protobuf.ByteString
      getL2Bytes(int index);

  /**
   * <code>repeated string l3 = 18;</code>
   * @return A list containing the l3.
   */
  java.util.List<String>
      getL3List();
  /**
   * <code>repeated string l3 = 18;</code>
   * @return The count of l3.
   */
  int getL3Count();
  /**
   * <code>repeated string l3 = 18;</code>
   * @param index The index of the element to return.
   * @return The l3 at the given index.
   */
  String getL3(int index);
  /**
   * <code>repeated string l3 = 18;</code>
   * @param index The index of the value to return.
   * @return The bytes of the l3 at the given index.
   */
  com.google.protobuf.ByteString
      getL3Bytes(int index);
}
